version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./shared:/app/shared
      - data:/app/data
    stdin_open: true
    tty: true
    command: 'npm run start'
    env_file:
      - .env
volumes:
  data:
