version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./shared:/app/shared
    stdin_open: true
    tty: true
    command: 'npm run start'
    restart: unless-stopped
    env_file:
      - .env
