version: "3.8"
services:
  app:
    build: .
    ports:
      - "3030:3000"
    volumes:
      - ./shared:/app/shared
    stdin_open: true
    tty: true
    command: "npm run start"
    restart: unless-stopped
    env_file:
      - .env
